### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by AnakinTrotter** [AnakinTrotter/Gender-Recognition-AI#1]
### **TO-DO LIST**
	- [x] Create a repository
	- [ ] Facial recognition
	- [ ] Parse data for training/testing
	- [ ] Train to high accuracy and save model
	- [ ] Apply accurate model to new data
	- [ ] Create GUI
